[Preference]
default_speak_interval = 0.5 # キャラクターが一文喋った後に待機する時間です

[OnFirstLoad]
message = [
    [
        """こんにちは!{my.name}です。私はこのデスクトップマスコットの案内役です。
まずは貴方の名前を教えて頂けますか?
{fill_name()}
{user.name}さんですね!これからよろしくお願いします!
{str.small("{2.name}さん!挨拶を!")}""",
        "よろしく",
        ["この子は{2.name}さんです!気が付いたころには傍にいて"]
    ]
]

[OnLoad]
message = [
    [
        "{check_profile()}"
    ]
]
