[random]
message = [
    [  # ここでは会話の基礎を学びます
        # 何も指定しない場合、設定ファイルのmodelに書かれた順で会話が切り替わります
        'こんにちは!これはランダムメッセージのサンプルです!character_1が喋ってると思います',
        # 末尾にカンマが来たため"character_1"から"キャラクター2"に会話が切り替わりました
        'やあやあ"キャラクター2"だよ',
        # また、'''で囲むことで改行を含んだ会話もできます
        '''
改行を含んだ会話もできます!
...見えていますか?'''
    ],
    [  # ここでは会話の切り替えを学びます
        # 会話の切り替えは、"--character キャラクター名"を指定することで行えます
        '--character "キャラクター2" キャラクター2から喋り始めたと思うがどうだろう?',
        'そして今はcharacter_1が喋ってると思います!',
        'こんな感じで雑談の順番を切り替えることができるわけだ',
        # また、会話の切り替えは頻繁に使用されるため"-c キャラクター名"でも切り替えが可能です
        '-c "キャラクター2" カンマが入ったが引き続きキャラクター2が喋ってるはずだよ',
        '-c "キャラクター2" つまり、こうすることで永遠に喋る続けることができるわけだが',
        '-c "キャラクター2" そんなことしないで下のようにしてね',
        '''
-c "キャラクター2" こうすればいちいち打たなくてもいっぱい話せるから
ね?
こうやって話そうか
''',
        "あの...そろそろ喋らせてください..."
    ],
    [  # TODO(実装): ここではキャラクターの感情の設定方法を学びます
        # ここではキャラクターの感情を"happy"に設定しています
        "--TODO happy なんだか楽しくなってきました!",
    ]
]

[on_click]
message = [
]
